language: cpp
script:
    - scripts/travis.sh $TRAVIS_ARGS --internal-libs
matrix:
  include:
  - name: "linux gcc release"
    os: linux
    env: TRAVIS_ARGS="--werror"
  - name: "linux clang debug"
    os: linux
    env: TRAVIS_ARGS="--debug --werror --clang"
  - name: "linux clang asan-ubsan"
    os: linux
    env: TRAVIS_ARGS="--debug --werror --asan-ubsan"
    # See <https://github.com/travis-ci/travis-ci/issues/9033>.
    sudo: true
  - name: "linux clang tidy"
    os: linux
    env: TRAVIS_ARGS="--debug --werror --tidy"
  - name: "macos release"
    os: osx
    osx_image: xcode8.3
    env: TRAVIS_ARGS="--werror"
  - name: "macos debug"
    os: osx
    osx_image: xcode8.3
    env: TRAVIS_ARGS="--debug --werror"
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
        packages:
            - g++-7
            - clang-tidy-7
