language: cpp
script:
    - scripts/travis.sh $TRAVIS_ARGS --internal-libs
matrix:
  include:
  - name: "linux gcc release"
    env: TRAVIS_ARGS="--werror"
  - name: "linux clang debug"
    env: TRAVIS_ARGS="--debug --werror --clang"
  - name: "linux clang sanitizers"
    env: TRAVIS_ARGS="--debug --werror --sanitizers"
    # See <https://github.com/travis-ci/travis-ci/issues/9033>.
    sudo: true
  - name: "linux clang tidy"
    env: TRAVIS_ARGS="--debug --werror --tidy"
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
        packages:
            - g++-7
            - clang-tidy-7
            - libnss3-dev
