version: "{build}"

os:
    - Visual Studio 2017

platform:
    - Win32

configuration:
    - Release
    - Debug

before_build:
    - cmake -H. -Bworkdir -DODFSIG_ENABLE_WERROR=ON

build:
  project: workdir\odfsig.sln
  parallel: true
  verbosity: normal

test_script:
  - cd workdir
  - ctest -V -C %CONFIGURATION%
