version: "{build}"

os:
    - Visual Studio 2017

platform:
    - Win32

configuration:
    - Release
    - Debug

before_build:
    - cmake -H. -Bworkdir -DODFSIG_ENABLE_WERROR=ON

build:
  project: workdir\odfsig.sln
  parallel: true
  verbosity: normal

after_build:
  - cd workdir
  - cpack -C %CONFIGURATION%

test_script:
  - cd tests
  - ctest -V -C %CONFIGURATION%

artifacts:
  - path: workdir\odfsig-*.zip
    name: Releases

deploy:
  provider: GitHub
  auth_token:
    secure: "H5xUFGYeaYpbbnEmicWbdGbZ1uWLe8BKokUu2sE6jCbdlGYi8lJi70ESYMFUv2fe"
  artifact: /odfsig-.*\.zip/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
    configuration: Release

branches:
  except:
    # build e.g. master, but not for/master
    - /for\/.*/
