version: "{build}"

os:
    - Visual Studio 2017

platform:
    - Win32

configuration:
    - Release
    - Debug

before_build:
    - cmake -H. -Bworkdir

build:
  project: workdir\odfsig.sln
  parallel: true
  verbosity: normal
