name: tests
on:
  push:
    branches-ignore:
      - 'private/**'
  pull_request:
    branches-ignore:
      - 'private/**'
  create:
    branches-ignore:
      - 'private/**'
jobs:
  linux-gcc-release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run make check
        run: |
          scripts/ci-build.sh
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: workdir/dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  linux-clang-debug:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run make check
        run: |
          scripts/ci-build.sh
  linux-clang-asan-ubsan:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run make check
        run: |
          scripts/ci-build.sh
  linux-clang-tidy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run make check
        run: |
          scripts/ci-build.sh
  linux-gcc-iwyu:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run make check
        run: |
          scripts/ci-build.sh
  macos-release:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run make check
        run: |
          scripts/ci-build.sh
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: workdir/dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  macos-debug:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run make check
        run: |
          scripts/ci-build.sh
  windows-release:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run make check
        run: |
          scripts/build.ps1 -config Release
  windows-debug:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run make check
        run: |
          scripts/build.ps1 -config Debug
