name: tests
on:
  push:
    branches-ignore:
      - 'private/**'
  pull_request:
    branches-ignore:
      - 'private/**'
jobs:
  linux-gcc-release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run make check
        run: |
          scripts/ci-build.sh
  linux-clang-debug:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run make check
        run: |
          scripts/ci-build.sh
  linux-clang-asan-ubsan:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run make check
        run: |
          scripts/ci-build.sh
  linux-valgrind:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run make check
        run: |
          scripts/ci-build.sh
  linux-clang-tidy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run make check
        run: |
          scripts/ci-build.sh
  linux-gcc-iwyu:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run make check
        run: |
          scripts/ci-build.sh
  # TODO: macos-release
  # TODO: macos-debug
